# Generated by Django 4.2.5 on 2023-12-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Email', models.CharField(max_length=150)),
                ('Phone_Number', models.IntegerField()),
                ('Message', models.TextField()),
            ],
        ),
    ]
