# Generated by Django 5.0 on 2023-12-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tododata',
            name='My_Image',
            field=models.ImageField(blank=True, null=True, upload_to='savedImages'),
        ),
    ]
