# Generated by Django 4.2.5 on 2023-12-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Phone_Number', models.IntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
